{
    "openapi": "3.0.0",
    "info": {
        "title": "API de uma Plataforma de Gerenciamento de Eventos Culturais",
        "description": "Essa API tem como objetivo a manipulação de dados de uma plataforma de gerenciamento de eventos culturais.",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "email": "thierryfulgencio@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/v1",
            "description": "API de teste"
        }
    ],
    "tags": [
        {
            "name": "Categorias",
            "description": "Operações relacionadas às categorias dos eventos culturais na plataforma."
        },
        {
            "name": "Locais",
            "description": "Operações relacionadas aos locais dos eventos culturais na plataforma."
        }
    ],
    "paths": {
        "/categoria": {
            "post": {
                "summary": "Cadastro de categoria",
                "description": "Essa rota é responsável por cadastrar uma nova categoria na plataforma.",
                "tags": [
                    "Categorias"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Categoria"
                            },
                            "examples": {
                                "categoria": {
                                    "value": {
                                        "nome": "Cinema Cultural"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "400": {
                        "description": "Categoria já cadastrada."
                    },
                    "201": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Categoria"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao criar categoria"
                    }
                }
            }
        },
        "/categorias": {
            "get": {
                "summary": "Buscar todas as categorias",
                "description": "Essa rota é responsável por buscar todas as categorias na plataforma.",
                "tags": [
                    "Categorias"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Categoria"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Nenhuma categoria encontrada"
                    },
                    "500": {
                        "description": "Erro ao buscar categorias"
                    }
                }
            }
        },
        "/categoria/{id}": {
            "get": {
                "summary": "Buscar categoria por ID",
                "description": "Essa rota é responsável por buscar uma categoria na plataforma.",
                "tags": [
                    "Categorias"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID da categoria",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Categoria"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada"
                    },
                    "500": {
                        "description": "Erro ao buscar categoria"
                    }
                }
            },
            "put": {
                "summary": "Atualizar categoria por ID",
                "description": "Essa rota é responsável por atualizar uma categoria na plataforma pelo seu ID.",
                "tags": [
                    "Categorias"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID da categoria",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Categoria"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Categoria"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada"
                    },
                    "500": {
                        "description": "Erro ao atualizar categoria"
                    }
                }
            },
            "delete": {
                "summary": "Deletar categoria por ID",
                "description": "Essa rota é responsável por deletar uma categoria na plataforma pelo seu ID.",
                "tags": [
                    "Categorias"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID da categoria",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada"
                    },
                    "500": {
                        "description": "Erro ao deletar categoria"
                    }
                }
            }
        },
        "/local": {
            "post": {
                "summary": "Cadastro de local",
                "description": "Essa rota é responsável por cadastrar um novo local na plataforma.",
                "tags": [
                    "Locais"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Local"
                            },
                            "examples": {
                                "local": {
                                    "value": {
                                        "nome": "Palacium",
                                        "cidade": "Cajazeiras",
                                        "CEP": "58900-000",
                                        "rua": "Rua do Xamegão",
                                        "numero": 29
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "400": {
                        "description": "Local já cadastrado."
                    },
                    "201": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Local"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao criar local"
                    }
                }
            }
        },
        "/locais": {
            "get": {
                "summary": "Buscar todos os locais",
                "description": "Essa rota é responsável por buscar todos os locais na plataforma.",
                "tags": [
                    "Locais"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Local"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Nenhum local encontrado"
                    },
                    "500": {
                        "description": "Erro ao buscar locais"
                    }
                }
            }
        },
        "/local/{id}": {
            "get": {
                "summary": "Buscar local por ID",
                "description": "Essa rota é responsável por buscar um local na plataforma.",
                "tags": [
                    "Locais"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do local",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Local"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Local não encontrado"
                    },
                    "500": {
                        "description": "Erro ao buscar local"
                    }
                }
            },
            "put": {
                "summary": "Atualizar local por ID",
                "description": "Essa rota é responsável por atualizar um local na plataforma pelo seu ID.",
                "tags": [
                    "Locais"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do local",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Local"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Local"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Local não encontrado"
                    },
                    "500": {
                        "description": "Erro ao atualizar local"
                    }
                }
            },
            "delete": {
                "summary": "Deletar local por ID",
                "description": "Essa rota é responsável por deletar um local na plataforma pelo seu ID.",
                "tags": [
                    "Locais"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do local",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Local não encontrado"
                    },
                    "500": {
                        "description": "Erro ao deletar local"
                    }
                }
            }
        },
        "/evento": {
            "post": {
                "summary": "Cadastro de Evento",
                "description": "Essa rota é responsável por cadastrar um novo evento na plataforma.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Evento"
                            },
                            "examples": {
                                "evento": {
                                    "value": {
                                        "nome": "Cinema na Praça",
                                        "descricao": "Filme de comédia",
                                        "data": "2022-12-10T19:00:00.000Z",
                                        "categoriaId": "a0a0a0a0aa0a0a0a0a",
                                        "localId": "a0a0a0a0a0a0aa0a0a"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "400": {
                        "description": "Evento já cadastrado."
                    },
                    "201": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao criar evento"
                    }
                }
            }
        },
        "/eventos": {
            "get": {
                "summary": "Buscar todos os eventos",
                "description": "Essa rota é responsável por buscar todos os eventos na plataforma.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Evento"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Nenhum evento encontrado"
                    },
                    "500": {
                        "description": "Erro ao buscar eventos"
                    }
                }
            }
        },
        "/evento/{id}": {
            "get": {
                "summary": "Buscar evento por ID",
                "description": "Essa rota é responsável por buscar um evento na plataforma.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do evento",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado"
                    },
                    "500": {
                        "description": "Erro ao buscar evento"
                    }
                }
            },
            "put": {
                "summary": "Atualização de Evento",
                "description": "Essa rota é responsável por atualizar um evento existente na plataforma.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID do evento a ser atualizado",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Evento"
                            },
                            "examples": {
                                "evento": {
                                    "value": {
                                        "nome": "Cinema na Praça",
                                        "descricao": "Filme de comédia",
                                        "data": "2022-12-10T19:00:00.000Z",
                                        "categoriaId": "a0a0a0a0aa0a0a0a0a",
                                        "localId": "a0a0a0a0a0a0aa0a0a"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado"
                    },
                    "500": {
                        "description": "Erro ao atualizar evento"
                    }
                }
            },
            "delete": {
                "summary": "Deletar evento por ID",
                "description": "Essa rota é responsável por deletar um evento na plataforma pelo seu ID.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do evento",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado"
                    },
                    "500": {
                        "description": "Erro ao deletar evento"
                    }
                }
            }
        },
        "/search": {
            "get": {
                "summary": "Buscar eventos",
                "description": "Essa rota é responsável por buscar eventos na plataforma com base em vários critérios.",
                "tags": [
                    "Eventos"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "evento",
                        "in": "query",
                        "description": "Nome do evento",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "categoria",
                        "in": "query",
                        "description": "Nome da categoria",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "local",
                        "in": "query",
                        "description": "Nome do local",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "dataInicio",
                        "in": "query",
                        "description": "Data de início do intervalo de busca",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "date-time"
                        }
                    },
                    {
                        "name": "dataFim",
                        "in": "query",
                        "description": "Data de fim do intervalo de busca",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "date-time"
                        }
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Erro na autenticação."
                    },
                    "404": {
                        "description": "Evento não encontrado"
                    },
                    "200": {
                        "description": "Uma lista de eventos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Evento"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar eventos"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Categoria": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                },
                "required": [
                    "nome"
                ]
            },
            "Local": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "cidade": {
                        "type": "string"
                    },
                    "CEP": {
                        "type": "string"
                    },
                    "rua": {
                        "type": "string"
                    },
                    "numero": {
                        "type": "integer"
                    },
                    "id": {
                        "type": "string"
                    }
                },
                "required": [
                    "nome",
                    "CEP",
                    "cidade",
                    "rua",
                    "numero"
                ]
            },
            "Evento": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "data": {
                        "type": "string"
                    },
                    "hora": {
                        "type": "string"
                    },
                    "categoriaId": {
                        "type": "string"
                    },
                    "localId": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "Categoria": {
                        "$ref": "#/components/schemas/Categoria"
                    },
                    "Local": {
                        "$ref": "#/components/schemas/Local"
                    }
                },
                "required": [
                    "nome",
                    "descricao",
                    "date",
                    "categoriaId",
                    "localId"
                ]
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}